---
- name: cheking the status of services
  hosts: all
  vars:
    services:
      - httpd
      - sshd
      - firewalld
  tasks:
    - name: looping through vars
      shell:
        cmd: "systemctl status {{ item }}"
      register: output
      tags: output
      loop: "{{services}}"
    - debug: msg="{{item.stdout_lines}}"
      loop: "{{output['results']}}"

